modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="teufox_additions"
version="1.0.0"
displayName="TeuFox Additions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="JoelA, MCreator"

[[dependencies.teufox_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.teufox_additions]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

